baseURL       = "https://hopeful-mcnulty-2711f7.netlify.app"
languageCode  = "fr-FR"
title         = "Roxo | NWS portfolio starter theme"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = ""
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "À propos"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = ""
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Me contacter"
    url     = "contact"
    weight  = 4

# Site Params
[params]
  logo = "logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "https://images.unsplash.com/photo-1487088678257-3a541e6e3922?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1867&q=80"
    heading               = "La créativité c'est percer le banal pour trouver le merveilleux."
    tagline               = ""
    primary_button        = ""
    primary_button_url    = "portfolio"
    secondary_button      = ""
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "Mes créations"
    subtitle  = ""

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact"
      address = "1 rue Marius Vallée, Sotteville-lès-Rouen 76300"
      phone   = "0636080351"
      email   = "acote@normandiewebschool.fr"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Site"
        [[params.footer.sitemap.link]]
          name = ""
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Portfolio"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = ""
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Me contacter"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Medium"
          url  = "#"
        [[params.footer.social.link]]
          name = "Behance"
          url  = "#"
        [[params.footer.social.link]]
          name = "Dribbble"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "We help brands:"
        description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"